path = './iSpaRo2024/2024-0205/2024-0205-130722/tables/w1___mi0_01.txt';
tab = fileread(path);
texline = "\\" +newline;
header = "\begin{table}[hb]" + newline ...
       + "\caption{$\omega=1.0$, $m_i=0.05$}" ...
       + "\label{table:ex1}" ...
       + "\centering" ...
       + "\scalebox{1}{" ...
       + " \begin{tabular}{c|cccccccc}" ...
       + " \hline" ...
       + "    $k_i \backslash d_i$ & 0.0 & 2.5 & 5.0 & 7.5 & 10 &p &p &p\\" ...
       + "    \hline";
footer = " \hline" ...
       + " \end{tabular}}" ...
       + "\end{table}";
dataTable = strrep(tab, newline, texline)